global:
  wifi_2_prop: 0.58
  wifi_5_prop: 0.42
  home_prop: 0.708333333
  outd_prop: 0.083333333
  work_prop: 0.208333333
devices:
  dect:
    dect_pwr: 250
    dect_dutycycle: 0.04
    brain:
      dect_ear_sar: 0.046356407
      dect_speaker_sar: 0.003210772
    body:
      dect_ear_sar: 0.011088893
      dect_speaker_sar: 0.002088857
  tblt:
    wifi_2_low_dutycycle: 0.009
    wifi_2_lowmed_dutycycle: 0.022
    wifi_2_medhigh_dutycycle: 0.138
    wifi_2_high_dutycycle: 0.671
    wifi_5_low_dutycycle: 0.024
    wifi_5_lowmed_dutycycle: 0.039
    wifi_5_medhigh_dutycycle: 0.054
    wifi_5_high_dutycycle: 0.495
    wifi_2_pwr: 100
    wifi_5_pwr: 200
    brain:
      tblt_2_sar: 0.001119463
      tblt_5_sar: 0.000320072
    body:
      tblt_2_sar: 0.000863117
      tblt_5_sar: 0.000553633
  lptp:
    wifi_2_low_dutycycle: 0.0086
    wifi_2_lowmed_dutycycle: 0.0220
    wifi_2_medhigh_dutycycle: 0.1378
    wifi_2_high_dutycycle: 0.6706
    wifi_5_low_dutycycle: 0.0243
    wifi_5_lowmed_dutycycle: 0.0386
    wifi_5_medhigh_dutycycle: 0.0537
    wifi_5_high_dutycycle: 0.4948
    wifi_2_pwr: 100
    wifi_5_pwr: 200
    legs_prop: 0.2
    tabl_prop: 0.8
    brain:
      wifi_2_legs_sar: 0.000034320
      wifi_2_tabl_sar: 0.000039139
      wifi_5_legs_sar: 0.000002239
      wifi_5_tabl_sar: 0.000009211
    body:
      wifi_2_legs_sar: 0.007105568
      wifi_2_tabl_sar: 0.003184117
      wifi_5_legs_sar: 0.005462274
      wifi_5_tabl_sar: 0.002186701
  wifi:
    wifi_2_pwr: 0.018
    wifi_5_pwr: 0.013
    brain:
      wifi_2_sar: 0.002618
      wifi_5_sar: 0.00055618
    body:
      wifi_2_sar: 0.003559655
      wifi_5_sar: 0.002402

  call:
    native_prop: 0.7
    data_prop: 0.115394
    wifi_prop: 0.184606
    native_2g_prop: 0.0075
    native_3g_prop: 0.0175
    native_4g_prop: 0.975
    native_5g_prop: 0
    data_2g_prop: 0
    data_3g_prop: 0.0175
    data_4g_prop: 0.66
    data_5g_prop: 0.3225
    data_2g_prop_no5g: 0
    data_3g_prop_no5g: 0.0175
    data_4g_prop_no5g: 0.9825
    data_5g_prop_no5g: 0
    native_2g_dutycycle: 0.12
    native_3g_dutycycle: 0.979275
    native_4g_dutycycle: 0.043038
    native_5g_dutycycle: 0.000
    native_2g_sub_ind_pwr: 1281.52
    native_2g_urb_ind_pwr: 374.87
    native_2g_rur_ind_pwr: 1371.23
    native_2g_sub_out_pwr: 383.9
    native_2g_urb_out_pwr: 173.81
    native_2g_rur_out_pwr: 433.90
    native_2g_travel_pwr: 383.9
    native_3g_sub_ind_pwr: 2.03
    native_3g_urb_ind_pwr: 0.97
    native_3g_rur_ind_pwr: 6.2
    native_3g_sub_out_pwr: 0.63
    native_3g_urb_out_pwr: 0.22
    native_3g_rur_out_pwr: 2.64
    native_3g_travel_pwr: 0.63
    native_4g_sub_ind_pwr: 159.3
    native_4g_urb_ind_pwr: 140.5
    native_4g_rur_ind_pwr: 178.1
    native_4g_sub_out_pwr: 109.75
    native_4g_urb_out_pwr: 94.3
    native_4g_rur_out_pwr: 125.2
    native_4g_travel_pwr: 109.75
    native_5g_sub_ind_pwr: 159.3
    native_5g_urb_ind_pwr: 140.5
    native_5g_rur_ind_pwr: 178.1
    native_5g_sub_out_pwr: 109.75
    native_5g_urb_out_pwr: 94.3
    native_5g_rur_out_pwr: 125.2
    native_5g_travel_pwr: 109.75
    data_2g_dutycycle: 0
    data_3g_dutycycle: 0.544567
    data_4g_dutycycle: 0.055613
    data_5g_dutycycle: 0.051400
    data_2g_sub_ind_pwr: 0
    data_2g_urb_ind_pwr: 0
    data_2g_rur_ind_pwr: 0
    data_2g_sub_out_pwr: 0
    data_2g_urb_out_pwr: 0
    data_2g_rur_out_pwr: 0
    data_2g_travel_pwr: 0
    data_3g_sub_ind_pwr: 2.04
    data_3g_urb_ind_pwr: 0.605
    data_3g_rur_ind_pwr: 6.28
    data_3g_sub_out_pwr: 0.87
    data_3g_urb_out_pwr: 0.26
    data_3g_rur_out_pwr: 2.68
    data_3g_travel_pwr: 0.87
    data_4g_sub_ind_pwr: 77.8985184
    data_4g_urb_ind_pwr: 64.1056383
    data_4g_rur_ind_pwr: 91.69139849
    data_4g_sub_out_pwr: 68.40566226
    data_4g_urb_out_pwr: 54.47906924
    data_4g_rur_out_pwr: 82.33225528
    data_4g_travel_pwr: 74.3
    data_5g_sub_ind_pwr: 49.13
    data_5g_urb_ind_pwr: 46.35
    data_5g_rur_ind_pwr: 51.91
    data_5g_sub_out_pwr: 40.045
    data_5g_urb_out_pwr: 36.92
    data_5g_rur_out_pwr: 43.17
    data_5g_travel_pwr: 31.52
    wifi_2_pwr: 100
    wifi_5_pwr: 200
    wifi_2_dutycycle: 0.02738
    wifi_5_dutycycle: 0.04930
    headp_face_prop: 0.333
    headp_pock_prop: 0.333
    headp_else_prop: 0.333
    bt_pwr: 0.16
    brain:
      data_2g_ear_sar: 0.08098
      data_2g_headp_face_sar: 0.0041018
      data_2g_headp_pock_sar: 0.00000365
      data_2g_headp_else_sar: 0
      data_2g_speaker_sar: 0.00726
      data_3g_ear_sar: 0.07618
      data_3g_headp_face_sar: 0.0038276
      data_3g_headp_pock_sar: 0.00000355
      data_3g_headp_else_sar: 0
      data_3g_speaker_sar: 0.00680
      data_4g_ear_sar: 0.07502
      data_4g_headp_face_sar: 0.0035994
      data_4g_headp_pock_sar: 0.00000438
      data_4g_headp_else_sar: 0
      data_4g_speaker_sar: 0.006546
      data_5g_ear_sar: 0.0055
      data_5g_headp_face_sar: 0.0006715
      data_5g_headp_pock_sar: 0.00000023
      data_5g_headp_else_sar: 0
      data_5g_speaker_sar: 0.000957
      native_2g_ear_sar: 0.08098
      native_2g_headp_face_sar: 0.0041018
      native_2g_headp_pock_sar: 0.00000365
      native_2g_headp_else_sar: 0
      native_2g_speaker_sar: 0.00726
      native_3g_ear_sar: 0.07618
      native_3g_headp_face_sar: 0.0038276
      native_3g_headp_pock_sar: 0.00000355
      native_3g_headp_else_sar: 0
      native_3g_speaker_sar: 0.00680
      native_4g_ear_sar: 0.07502
      native_4g_headp_face_sar: 0.0035994
      native_4g_headp_pock_sar: 0.00000438
      native_4g_headp_else_sar: 0
      native_4g_speaker_sar: 0.006546
      native_5g_ear_sar: 0.0055
      native_5g_headp_face_sar: 0.0006715
      native_5g_headp_pock_sar: 0.00000023
      native_5g_headp_else_sar: 0
      native_5g_speaker_sar: 0.000957
      wifi_2_ear_sar: 0.026727749
      wifi_2_headp_face_sar: 0.001119463
      wifi_2_headp_pock_sar: 0.000000328
      wifi_2_headp_else_sar: 0
      wifi_2_speaker_sar: 0.001556721
      wifi_5_ear_sar: 0.001040371
      wifi_5_headp_face_sar: 0.000320072
      wifi_5_headp_pock_sar: 0.000000000014
      wifi_5_headp_else_sar: 0
      wifi_5_speaker_sar: 0.000332549
      bt_phone_face_sar: 0.000999468
      bt_phone_pock_sar: 0.000000475
      bt_phone_else_sar: 0
      bt_headp_sar: 0.01699017
    body:
      native_2g_ear_sar: 0.011697
      native_2g_headp_face_sar: 0.001073
      native_2g_headp_pock_sar: 0.009881
      native_2g_headp_else_sar: 0
      native_2g_speaker_sar: 0.002308
      native_3g_ear_sar: 0.011424
      native_3g_headp_face_sar: 0.001062
      native_3g_headp_pock_sar: 0.009435
      native_3g_headp_else_sar: 0
      native_3g_speaker_sar: 0.002225
      native_4g_ear_sar: 0.011416
      native_4g_headp_face_sar: 0.001036
      native_4g_headp_pock_sar: 0.009394
      native_4g_headp_else_sar: 0
      native_4g_speaker_sar: 0.002231
      native_5g_ear_sar: 0.009308
      native_5g_headp_face_sar: 0.0007263
      native_5g_headp_pock_sar: 0.0040845
      native_5g_headp_else_sar: 0
      native_5g_speaker_sar: 0.004084
      data_2g_ear_sar: 0.011697
      data_2g_headp_face_sar: 0.001073
      data_2g_headp_pock_sar: 0.009881
      data_2g_headp_else_sar: 0
      data_2g_speaker_sar: 0.002308
      data_3g_ear_sar: 0.011424
      data_3g_headp_face_sar: 0.001062
      data_3g_headp_pock_sar: 0.009435
      data_3g_headp_else_sar: 0
      data_3g_speaker_sar: 0.002225
      data_4g_ear_sar: 0.011416
      data_4g_headp_face_sar: 0.001036
      data_4g_headp_pock_sar: 0.009394
      data_4g_headp_else_sar: 0
      data_4g_speaker_sar: 0.002231
      data_5g_ear_sar: 0.009308
      data_5g_headp_face_sar: 0.0007263
      data_5g_headp_pock_sar: 0.0040845
      data_5g_headp_else_sar: 0
      data_5g_speaker_sar: 0.004084
      wifi_2_ear_sar: 0.010022773
      wifi_2_headp_face_sar: 0.000863117
      wifi_2_headp_pock_sar: 0.006278143
      wifi_2_headp_else_sar: 0
      wifi_2_speaker_sar: 0.001762495
      wifi_5_ear_sar: 0.006538522
      wifi_5_headp_face_sar: 0.000553633
      wifi_5_headp_pock_sar: 0.002473388
      wifi_5_headp_else_sar: 0
      wifi_5_speaker_sar: 0.00127148
      bt_phone_face_sar: 0.000860849
      bt_phone_pock_sar: 0.010153247
      bt_phone_else_sar: 0
      bt_headp_sar: 0.009862
  data:
    data_2g_prop: 0
    data_3g_prop: 0.0175
    data_4g_prop: 0.6600
    data_5g_prop: 0.3225
    data_2g_prop_no5g: 0
    data_3g_prop_no5g: 0.0175
    data_4g_prop_no5g: 0.9825
    data_5g_prop_no5g: 0
    data_3g_low_dutycycle: 0.438
    data_3g_lowmed_dutycycle: 0.505
    data_3g_medhigh_dutycycle: 0.542
    data_3g_high_dutycycle: 0.783
    data_3g_sub_ind_pwr: 114.025
    data_3g_sub_out_pwr: 48.641
    data_3g_urb_ind_pwr: 1.837
    data_3g_urb_out_pwr: 0.783
    data_3g_rur_ind_pwr: 167.109
    data_3g_rur_out_pwr: 71.285
    data_3g_travel_pwr: 48.640
    data_4g_low_dutycycle: 0.006
    data_4g_lowmed_dutycycle: 0.056
    data_4g_medhigh_dutycycle: 0.134
    data_4g_high_dutycycle: 1
    data_4g_sub_ind_pwr: 77.899
    data_4g_sub_out_pwr: 68.406
    data_4g_urb_ind_pwr: 64.106
    data_4g_urb_out_pwr: 54.479
    data_4g_rur_ind_pwr: 91.691
    data_4g_rur_out_pwr: 82.332
    data_4g_travel_pwr: 74.300
    data_5g_low_dutycycle: 0.005
    data_5g_lowmed_dutycycle: 0.051
    data_5g_medhigh_dutycycle: 0.216
    data_5g_high_dutycycle: 1
    data_5g_sub_ind_pwr: 49.130
    data_5g_sub_out_pwr: 40.045
    data_5g_urb_ind_pwr: 46.350
    data_5g_urb_out_pwr: 36.920
    data_5g_rur_ind_pwr: 51.910
    data_5g_rur_out_pwr: 43.170
    data_5g_travel_pwr: 31.520
    wifi_2_low_dutycycle: 0.0086
    wifi_2_lowmed_dutycycle: 0.0220
    wifi_2_medhigh_dutycycle: 0.1378
    wifi_2_high_dutycycle: 0.6706
    wifi_2_pwr: 100.00
    wifi_5_low_dutycycle: 0.0243
    wifi_5_lowmed_dutycycle: 0.0386
    wifi_5_medhigh_dutycycle: 0.0537
    wifi_5_high_dutycycle: 0.4948
    wifi_5_pwr: 200.00
    brain:
      data_3g_sar: 0.003827632
      data_4g_sar: 0.003599419
      data_5g_sar: 0.000671496
      wifi_2_sar: 0.001119463
      wifi_5_sar: 0.000320072
    body:
      data_3g_sar: 0.001061719
      data_4g_sar: 0.001036151
      data_5g_sar: 0.000726276
      wifi_2_sar: 0.000863117
      wifi_5_sar: 0.000553633
  farf:
    home_urb_pwr_Other: 0.44846
    out_urb_pwr_Other: 1.29337
    work_urb_pwr_Other: 0.63857
    home_sub_pwr_Other: 0.26832
    out_sub_pwr_Other: 0.77384
    work_sub_pwr_Other: 0.38317
    home_rur_pwr_Other: 0.08818
    out_rur_pwr_Other: 0.25432
    work_rur_pwr_Other: 0.12777
    travel_pwr_Other: 0.65563
    home_urb_pwr_AT: 0.52844
    out_urb_pwr_AT: 1.52405
    work_urb_pwr_AT: 0.10779
    home_sub_pwr_AT: 0.36728
    out_sub_pwr_AT: 1.05924
    work_sub_pwr_AT: 0.24779
    home_rur_pwr_AT: 0.20611
    out_rur_pwr_AT: 0.59443
    work_rur_pwr_AT: 0.38779
    travel_pwr_AT: 1.03419
    home_urb_pwr_BE: 0.29898
    out_urb_pwr_BE: 0.86227
    work_urb_pwr_BE: 0.21893
    home_sub_pwr_BE: 0.19152
    out_sub_pwr_BE: 0.55234
    work_sub_pwr_BE: 0.15295
    home_rur_pwr_BE: 0.08405
    out_rur_pwr_BE: 0.24240
    work_rur_pwr_BE: 0.08696
    travel_pwr_BE: 0.48639
    home_urb_pwr_FR: 1.23842
    out_urb_pwr_FR: 3.57163
    work_urb_pwr_FR: 1.72137
    home_sub_pwr_FR: 0.64514
    out_sub_pwr_FR: 1.86059
    work_sub_pwr_FR: 0.89709
    home_rur_pwr_FR: 0.05186
    out_rur_pwr_FR: 0.14955
    work_rur_pwr_FR: 0.07282
    travel_pwr_FR: 1.15457
    home_urb_pwr_HU: 0.39519
    out_urb_pwr_HU: 1.13973
    work_urb_pwr_HU: 0.31620
    home_sub_pwr_HU: 0.23006
    out_sub_pwr_HU: 0.66351
    work_sub_pwr_HU: 0.28185
    home_rur_pwr_HU: 0.06494
    out_rur_pwr_HU: 0.18729
    work_rur_pwr_HU: 0.24751
    travel_pwr_HU: 0.43946
    home_urb_pwr_IT: 0.30335
    out_urb_pwr_IT: 0.87488
    work_urb_pwr_IT: 0.42165
    home_sub_pwr_IT: 0.19381
    out_sub_pwr_IT: 0.55894
    work_sub_pwr_IT: 0.22763
    home_rur_pwr_IT: 0.08426
    out_rur_pwr_IT: 0.24301
    work_rur_pwr_IT: 0.03360
    travel_pwr_IT: 0.28102
    home_urb_pwr_NL: 0.35229
    out_urb_pwr_NL: 1.01601
    work_urb_pwr_NL: 0.48967
    home_sub_pwr_NL: 0.21582
    out_sub_pwr_NL: 0.62243
    work_sub_pwr_NL: 0.30055
    home_rur_pwr_NL: 0.07935
    out_rur_pwr_NL: 0.22885
    work_rur_pwr_NL: 0.11143
    travel_pwr_NL: 0.66145
    home_urb_pwr_PL: 0.64822
    out_urb_pwr_PL: 1.86949
    work_urb_pwr_PL: 1.59295
    home_sub_pwr_PL: 0.36070
    out_sub_pwr_PL: 1.04027
    work_sub_pwr_PL: 0.80746
    home_rur_pwr_PL: 0.07318
    out_rur_pwr_PL: 0.21105
    work_rur_pwr_PL: 0.02197
    travel_pwr_PL: 0.83839
    home_urb_pwr_ES: 0.29184
    out_urb_pwr_ES: 0.84166
    work_urb_pwr_ES: 1.00924
    home_sub_pwr_ES: 0.21100
    out_sub_pwr_ES: 0.60854
    work_sub_pwr_ES: 0.59602
    home_rur_pwr_ES: 0.13017
    out_rur_pwr_ES: 0.37542
    work_rur_pwr_ES: 0.18280
    travel_pwr_ES: 0.59829
    home_urb_pwr_CH: 0.12361
    out_urb_pwr_CH: 0.35650
    work_urb_pwr_CH: 0.08502
    home_sub_pwr_CH: 0.09261
    out_sub_pwr_CH: 0.26709
    work_sub_pwr_CH: 0.08577
    home_rur_pwr_CH: 0.06161
    out_rur_pwr_CH: 0.17769
    work_rur_pwr_CH: 0.08652
    travel_pwr_CH: 0.31278
    home_urb_pwr_UK: 0.30425
    out_urb_pwr_UK: 0.87747
    work_urb_pwr_UK: 0.42290
    home_sub_pwr_UK: 0.17527
    out_sub_pwr_UK: 0.50547
    work_sub_pwr_UK: 0.23458
    home_rur_pwr_UK: 0.04628
    out_rur_pwr_UK: 0.13347
    work_rur_pwr_UK: 0.04626
    travel_pwr_UK: 0.74977
    
    brain:
      sar: 0.005491315
    body:
      sar: 0.004594286
  smartwatch:
    watch_pwr_active: 1
    watch_pwr_passive: 0.002
    watch_phone_pwr: 0.002
    brain:
      watch_sar: 0.00002359
      watch_phone_sar: 0.00036953
    body:
      watch_sar: 0.01063377
      watch_phone_sar: 0.00235662
  headphones:
    headp_pwr: 0.002
    headp_phone_pwr: 0.16
    brain:
      headp_sar: 0.020049
      headp_phone_sar: 0.000370
    body:
      headp_sar: 0.014058
      headp_phone_sar: 0.002357
  hotspot:
    hotspot_pwr: 5.1755728
    brain:
      hotspot_sar: 0.000370
    body:
      hotspot_sar: 0.002357
  vr:
    vr_2_pwr: 100
    vr_5_pwr: 200
    vr_2_dutycycle: 0.138
    vr_5_dutycycle: 0.054
    vr_online_prop: 0.5
    brain:
      vr_2_sar: 0.02672775
      vr_5_sar: 0.00104037
    body:
      vr_2_sar: 0.01002277
      vr_5_sar: 0.00653852
  gaming:
    gaming_online_prop: 0.5
    gaming_2_dutycycle: 0.022
    gaming_5_dutycycle: 0.028
    gaming_2_pwr: 100
    gaming_5_pwr: 200
    brain:
      gaming_2_sar: 0.001119
      gaming_5_sar: 0.000320
    body:
      gaming_2_sar: 0.000863
      gaming_5_sar: 0.000554





