dect_pwr: 8.5
dect_duty_factor: 0.185
dect_ear_prop: 0.9
dect_speaker_prop: 0.1
dect_ear_brain_sar: 0.034926
dect_speaker_brain_sar: 0.002603877
dect_ear_body_sar: 0.007
dect_speaker_body_sar: 0.0021
tblt_2.4_prop: 0.5
tblt_5.0_prop: 0.5
tblt_2.4_pwr: 11.7588
tblt_5.0_pwr: 11.7588
tblt_2.4_brain_sar: 0.000999468
tblt_5.0_brain_sar: 0.000163091
tblt_2.4_body_sar: 0.0009
tblt_5.0_body_sar: 0.000999468230864152
lptp_2.4_prop: 0.5
lptp_5.0_prop: 0.5
lptp_2.4_pwr: 11.7588
lptp_5.0_pwr: 11.7588
lptp_legs_prop: 0.2
lptp_tabl_prop: 0.8
lptp_2.4_legs_brain_sar: 5.18942E-05
lptp_2.4_tabl_brain_sar: 6.89201E-05
lptp_5.0_legs_brain_sar: 6.75E-06
lptp_5.0_tabl_brain_sar: 9.50E-06
lptp_2.4_legs_body_sar: 0.005
lptp_2.4_tabl_body_sar: 0.00125
lptp_5.0_legs_body_sar: 0.005
lptp_5.0_tabl_body_sar: 0.00125
wifi_2.4_prop: 0.5
wifi_5.0_prop: 0.5
wifi_2.4_pwr: 0.017
wifi_5.0_pwr: 0.016
wifi_2.4_brain_sar: 0.00133
wifi_5.0_brain_sar: 0.00133
wifi_2.4_body_sar: 0.005295
wifi_5.0_body_sar: 0.005295
call_native_prop: 0.7
call_data_prop: 0.21
call_wifi_prop: 0.09
call_native_pwr: 6.78
call_data_pwr: 5.96
call_wifi_pwr: 2.738
call_ear_prop: 0.66
call_headp_prop: 0.17
call_speaker_prop: 0.17
call_native_ear_brain_sar: 0.061597475
call_native_headp_brain_sar: 0.001005179
call_native_speaker_brain_sar: 0.005168032
call_data_ear_brain_sar: 0.061597475
call_data_headp_brain_sar: 0.000332981
call_data_speaker_brain_sar: 0.005168032
call_2.4_prop: 0.5
call_5.0_prop: 0.5
call_wifi_2.4_ear_brain_sar: 0.016377585
call_wifi_2.4_headp_brain_sar: 0.000332981
call_wifi_2.4_speaker_brain_sar: 0.001272228
call_wifi_5.0_ear_brain_sar: 0.000606727
call_wifi_5.0_headp_brain_sar: 5.43165E-05
call_wifi_5.0_speaker_brain_sar: 0.000169973



