global:
  wifi_2_prop: 0.58
  wifi_5_prop: 0.42
  home_prop: 0.71
  outd_prop: 0.08
  work_prop: 0.21
  tech_3g_prop_5gno: 0.1
  tech_4g_prop_5gno: 0.9
  tech_5g_prop_5gno: 0
  tech_3g_prop: 0.1
  tech_4g_prop: 0.75
  tech_5g_prop: 0.15
devices:
  dect:
    shared:
      dect_pwr: 250
      dect_duty_factor: 0.04
    brain:
      dect_ear_sar: 0.034926
      dect_speaker_sar: 0.002603877
    body:
      dect_ear_sar: 0.007025455
      dect_speaker_sar: 0.002116649
  tblt:
    shared:
      wifi_2_low_dutycycle: 0.009
      wifi_2_lowmed_dutycycle: 0.025
      wifi_2_medhigh_dutycycle: 0.176
      wifi_2_high_dutycycle: 0.669
      wifi_5_low_dutycycle: 0.03055
      wifi_5_lowmed_dutycycle: 0.052275
      wifi_5_medhigh_dutycycle: 0.064
      wifi_5_high_dutycycle: 0.14515
      wifi_2_pwr: 100
      wifi_5_pwr: 200
    brain:
      tblt_2_sar: 0.000999468
      tblt_5_sar: 0.000163091
    body:
      tblt_2_sar: 0.000860849
      tblt_5_sar: 0.000586175
  lptp:
    shared:
      wifi_2_low_dutycycle: 0.009
      wifi_2_lowmed_dutycycle: 0.025
      wifi_2_medhigh_dutycycle: 0.176
      wifi_2_high_dutycycle: 0.669
      wifi_5_low_dutycycle: 0.03055
      wifi_5_lowmed_dutycycle: 0.052275
      wifi_5_medhigh_dutycycle: 0.064
      wifi_5_high_dutycycle: 0.14515
      wifi_2_pwr: 100
      wifi_5_pwr: 200
      legs_prop: 0.2
      tabl_prop: 0.8
    brain:
      wifi_2_legs_sar: 5.18942E-05
      wifi_2_tabl_sar: 6.89201E-05
      wifi_5_legs_sar: 6.75E-06
      wifi_5_tabl_sar: 9.50E-06
    body:
      wifi_2_legs_sar: 0.005001918
      wifi_2_tabl_sar: 0.001261547
      wifi_5_legs_sar: 0.003303364
      wifi_5_tabl_sar: 0.000883944
  wifi:
    shared:
      wifi_2_pwr: 0.017
      wifi_5_pwr: 0.016
    brain:
      wifi_2_sar: 0.00133
      wifi_5_sar: 0.00133
    body:
      wifi_2_sar: 0.005295
      wifi_5_sar: 0.005295
  call:
    shared:
      native_prop: 0.7
      data_prop: 0.16
      wifi_prop: 0.14
      native_2g_prop: 0.03
      native_3g_prop: 0.09
      native_4g_prop: 0.735
      native_5g_prop: 0.145
      native_2g_dutycycle: 0.12
      native_3g_dutycycle: 0.98
      native_4g_dutycycle: 0.0389
      native_5g_dutycycle: 0.0389
      native_2g_sub_indo_pwr: 1281.52
      native_2g_urb_indo_pwr: 374.8682087
      native_2g_rur_indo_pwr: 1371.23
      native_2g_sub_outd_pwr: 383.90
      native_2g_urb_outd_pwr: 173.81
      native_2g_rur_outd_pwr: 433.90
      native_2g_travel_pwr: 383.9
      native_3g_sub_indo_pwr: 2.03
      native_3g_urb_indo_pwr: 0.97
      native_3g_rur_indo_pwr: 6.2
      native_3g_sub_outd_pwr: 0.63
      native_3g_urb_outd_pwr: 0.22
      native_3g_rur_outd_pwr: 2.64
      native_3g_travel_pwr: 0.63
      native_4g_sub_indo_pwr: 159.3
      native_4g_urb_indo_pwr: 140.5
      native_4g_rur_indo_pwr: 178.1
      native_4g_sub_outd_pwr: 109.75
      native_4g_urb_outd_pwr: 94.3
      native_4g_rur_outd_pwr: 125.2
      native_4g_travel_pwr: 109.75
      native_5g_sub_indo_pwr: 159.3
      native_5g_urb_indo_pwr: 140.5
      native_5g_rur_indo_pwr: 178.1
      native_5g_sub_outd_pwr: 109.75
      native_5g_urb_outd_pwr: 94.3
      native_5g_rur_outd_pwr: 125.2
      native_5g_travel_pwr: 109.75
      data_3g_dutycycle: 0.54
      data_4g_dutycycle: 0.0904
      data_5g_dutycycle: 0.0491
      data_3g_sub_indo_pwr: 2.04
      data_3g_urb_indo_pwr: 0.605
      data_3g_rur_indo_pwr: 6.28
      data_3g_sub_outd_pwr: 0.87
      data_3g_urb_outd_pwr: 0.01
      data_3g_rur_outd_pwr: 2.68
      data_3g_travel_pwr: 0.87
      data_4g_sub_indo_pwr: 77.8985184
      data_4g_urb_indo_pwr: 64.1056383
      data_4g_rur_indo_pwr: 91.69139849
      data_4g_sub_outd_pwr: 68.40566226
      data_4g_urb_outd_pwr: 54.47906924
      data_4g_rur_outd_pwr: 82.33225528
      data_4g_travel_pwr: 74.3
      data_5g_sub_indo_pwr: 49.13
      data_5g_urb_indo_pwr: 46.35
      data_5g_rur_indo_pwr: 51.91
      data_5g_sub_outd_pwr: 40.045
      data_5g_urb_outd_pwr: 36.92
      data_5g_rur_outd_pwr: 43.17
      data_5g_travel_pwr: 31.52
      wifi_2_pwr: 100
      wifi_5_pwr: 200
      wifi_2_duty_cycle: 0.02738
      wifi_5_duty_cycle: 0.04385
      headp_face_prop: 0.333
      headp_pock_prop: 0.333
      headp_else_prop: 0.333
      headp_phone_bt_pwr: 0.15
    brain:
      native_ear_sar: 0.056245281
      native_headp_face_sar: 0.002917897
      native_headp_pock_sar: 0.000009
      native_headp_else_sar: 0
      native_speaker_sar: 0.004814895
      data_ear_sar: 0.056245281
      data_headp_face_sar: 0.002917897
      data_headp_pock_sar: 0.000009
      data_headp_else_sar: 0
      data_speaker_sar: 0.004814895
      wifi_2_ear_sar: 0.016377585
      wifi_2_headp_face_sar: 0.000999468
      wifi_2_headp_pock_sar: 4.75109794184096E-07
      wifi_2_headp_else_sar: 0
      wifi_2_speaker_sar: 0.001272228
      wifi_5_ear_sar: 0.000606727
      wifi_5_headp_face_sar: 0.000163091
      wifi_5_headp_pock_sar: 0.000000021
      wifi_5_headp_else_sar: 0
      wifi_5_speaker_sar: 0.000169973
      bt_phone_face_sar: 0.000999468
      bt_phone_pock_sar: 0.000000475
      bt_phone_else_sar: 0
      bt_headp_sar: 0.01699017
    body:
      native_ear_sar: 0.0072926
      native_headp_face_sar: 0.000994539
      native_headp_pock_sar: 0.010499677
      native_headp_else_sar: 0
      native_speaker_sar: 0.002126318
      data_ear_sar: 0.0072926
      data_headp_face_sar: 0.000994539
      data_headp_pock_sar: 0.010499677
      data_headp_else_sar: 0
      data_speaker_sar: 0.002126318
      wifi_2_ear_sar: 0.005180701
      wifi_2_headp_face_sar: 0.000860849
      wifi_2_headp_pock_sar: 0.010153247
      wifi_2_headp_else_sar: 0
      wifi_2_speaker_sar: 0.001750505
      wifi_5_ear_sar: 0.003516185
      wifi_5_headp_face_sar: 0.000586175 
      wifi_5_headp_pock_sar: 0.002646374
      wifi_5_headp_else_sar: 0
      wifi_5_speaker_sar: 0.001182344
      bt_phone_face_sar: 0.0009
      bt_phone_pock_sar: 0.01015
      bt_phone_else_sar: 0
      bt_headp_sar: 0.009862
  data:
    shared:
      data_3g_low_ind_dutycycle: 0.438
      data_3g_lowmed_ind_dutycycle: 0.544566667
      data_3g_medhigh_ind_dutycycle: 0.592
      data_3g_high_ind_dutycycle: 0.810866667
      data_3g_suburb_ind_pwr: 114.02
      data_3g_suburb_out_pwr: 48.64
      data_3g_urb_ind_pwr: 1.84
      data_3g_urb_out_pwr: 0.78
      data_3g_rural_ind_pwr: 167.11
      data_3g_rural_out_pwr: 71.29
      data_3g_travel_pwr: 48.64
      data_4g_low_ind_dutycycle: 0.008506
      data_4g_lowmed_ind_dutycycle: 0.08506
      data_4g_medhigh_ind_dutycycle: 0.20818
      data_4g_high_ind_dutycycle: 1
      data_4g_suburb_ind_pwr: 77.899
      data_4g_suburb_out_pwr: 68.406
      data_4g_urb_ind_pwr: 64.106
      data_4g_urb_out_pwr: 54.479
      data_4g_rural_ind_pwr: 91.691
      data_4g_rural_out_pwr: 82.332
      data_4g_travel_pwr: 74.300
      data_5g_low_ind_dutycycle: 0.0048249
      data_5g_lowmed_ind_dutycycle: 0.048249
      data_5g_medhigh_ind_dutycycle: 0.347031
      data_5g_high_ind_dutycycle: 1
      data_5g_suburb_ind_pwr: 49.130
      data_5g_suburb_out_pwr: 40.045
      data_5g_urb_ind_pwr: 46.350
      data_5g_urb_out_pwr: 36.920
      data_5g_rural_ind_pwr: 51.910
      data_5g_rural_out_pwr: 43.170
      data_5g_travel_pwr: 31.520
      wifi_2_low_dutycycle: 0.009
      wifi_2_lowmed_dutycycle: 0.025
      wifi_2_medhigh_dutycycle: 0.176
      wifi_2_high_dutycycle: 0.669
      wifi_2_pwr: 100.00
      wifi_5_low_dutycycle: 0.03055
      wifi_5_lowmed_dutycycle: 0.052275
      wifi_5_medhigh_dutycycle: 0.064
      wifi_5_high_dutycycle: 0.14515
      wifi_5_pwr: 200.00
    brain:
      data_face_sar: 0.002917897
      wifi_2_face_sar: 0.000999468
      wifi_5_face_sar: 0.000163091
    body:
      data_face_sar: 0.000994539
      wifi_2_face_sar: 0.000861
      wifi_5_face_sar: 0.000586175
  farf:
    shared:
      home_urban_pwr: 0.490
      outdoor_urban_pwr: 0.930
      work_urban_pwr: 0.870
      home_suburb_pwr: 0.268
      outdoor_suburb_pwr: 0.613
      work_suburb_pwr: 0.538
      home_rural_pwr: 0.045
      outdoor_rural_pwr: 0.295
      work_rural_pwr: 0.205
      travel_pwr: 0.640
    brain:
      sar: 0.0083632
    body:
      sar: 0.007579411
  watch:
    shared:
      watch_pwr: 0.00008
      watch_phone_pwr: 0.00008
    brain:
      watch_sar: 0.0000017
      watch_phone_sar: 0.000329981    
    body:
      watch_sar: 0.01365
      watch_phone_sar: 0.0036465
  tracker:
    shared:
      tracker_pwr: 0.00008
      tracker_phone_pwr: 0.00008
    brain:
      tracker_sar: 0.000031
      tracker_phone_sar: 0.000329981
    body:      
      tracker_sar: 0.0118
      tracker_phone_sar: 0.0036465
  headp:
    shared:
      headp_pwr: 0.00008
      headp_phone_pwr: 0.15
    brain:
      headp_sar: 0.016990171
      headp_phone_sar: 0.000329981
    body:      
      headp_sar: 0.009862
      headp_phone_sar: 0.0036465     
  hots:
    shared:
      hots_pwr: 5.595
    brain:
      hots_sar: 0.000329981
    body:
      hots_sar: 0.0036465
  vr:
    shared:
      vr_pwr: 10
    brain:
      vr_sar: 0.000606721
    body:
      vr_sar: 0.0035162
  smah:
    shared:
      smah_pwr: 1.64109
      smah_active_prop: 0.01
    brain: 
      smah_sar: 0.00133
    body:
      smah_sar: 0.009862
  game:
    shared:
      game_online_prop: 0.25
      game_2_dutycycle: 0.0276
      game_5_dutycycle: 0.0276
      game_2_pwr: 100
      game_5_pwr: 200
    brain:
      game_2_sar: 0.000999468
      game_5_sar: 0.000163091
    body:
      game_2_sar: 0.000860849
      game_5_sar: 0.000586175




